name = livingcavesmobs
title = Living Caves Mobs
description = Adds mobs to for livingcaves mod.
depends = default, livingcaves, mobs, tnt
optional_depends = ethereal, naturalbiomes
min_minetest_version = 5.0.0
